# .travis-git-aws.yml
# .travis file used to automatically setup the images from Github to AWS
sudo: required
services:
  - docker

before_install:
  # dockerid/name_of_your_image
  - docker build -t alexbr9007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexbr9007/react-test npm test -- --coverage

after_success:
  - docker build -t alexbr9007/multi-images-client ./client
  - docker build -t alexbr9007/multi-images-nginx ./nginx
  - docker build -t alexbr9007/multi-images-server ./server
  - docker build -t alexbr9007/multi-images-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alexbr9007/multi-images-client
  - docker push alexbr9007/multi-images-nginx
  - docker push alexbr9007/multi-images-server
  - docker push alexbr9007/multi-images-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker-dockerhub-ci
  env: MultiDockerDockerhubCi-env
  bucket_name: elasticbeanstalk-us-west-2-401387916447
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
